import Logo from "@/app/DashboardLayout/layout/shared/logo/Logo";
import CardBox from "@/app/components/shared/CardBox";
import React from "react";
import SocialButtons from "../../authforms/SocialButtons";
import AuthLogin from "../../authforms/AuthLogin";
import Link from "next/link";
import type { Metadata } from "next";
import rightBgimg from "/public/images/backgrounds/leaf-right.png"
import leftBgimg from "/public/images/backgrounds/leaf-left.png"
import Image from "next/image";
import FullLogo from "@/app/DashboardLayout/layout/shared/logo/FullLogo";
import AuthRegister from "../../authforms/AuthRegister";
export const metadata: Metadata = {
  title: "Boxed Login Authentication",
  description: "Generated by create next app",
};
const BoxedLogin = () => {
  return (
    <>
      <div className="relative min-h-screen overflow-y-auto bg-lightsubtle dark:bg-dark">
        {/* Imagen izquierda */}
        <div className="absolute start-0 bottom-0 z-1 md:block hidden">
          <Image src={leftBgimg} alt="img" />
        </div>

        {/* Contenido centrado */}
        <div className="flex min-h-screen justify-center items-center px-4">
          <CardBox className="md:w-[450px] w-full border-none">
            <div className="mx-auto mb-4">
              <FullLogo />
            </div>

            <AuthRegister />

            <div className="flex gap-2 text-base text-dark dark:text-white font-medium mt-6 items-center justify-center">
              <p>Ya tienes una cuenta?</p>
              <Link
                href={"/auth/auth2/login"}
                className="text-primary text-sm font-medium"
              >
                Iniciar Sesión
              </Link>
            </div>
          </CardBox>
        </div>

        {/* Imagen derecha */}
        <div className="absolute end-0 bottom-0 z-1 md:block hidden">
          <Image src={rightBgimg} alt="img" />
        </div>
      </div>
    </>
  );
};


export default BoxedLogin;
