name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            japipe05/mssinergy-nextjs-dock:latest
            japipe05/mssinergy-nextjs-dock:v1.0.${{ github.run_number }}
          cache-from: type=registry,ref=japipe05/mssinergy-nextjs-dock:buildcache
          cache-to: type=registry,ref=japipe05/mssinergy-nextjs-dock:buildcache,mode=max
